/*
 * API Avito shop
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InfoResponseCoinHistoryReceived struct {
	// Имя пользователя, который отправил монеты.
	FromUser string `json:"fromUser,omitempty"`
	// Количество полученных монет.
	Amount int32 `json:"amount,omitempty"`
}
