/*
 * API Avito shop
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InfoResponseInventory struct {
	// Тип предмета.
	Type_ string `json:"type,omitempty"`
	// Количество предметов.
	Quantity int32 `json:"quantity,omitempty"`
}
