/*
 * API Avito shop
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InfoResponseCoinHistorySent struct {
	// Имя пользователя, которому отправлены монеты.
	ToUser string `json:"toUser,omitempty"`
	// Количество отправленных монет.
	Amount int32 `json:"amount,omitempty"`
}
