version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: avito_shop
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    environment:
      DOCKER_ENV: "true"
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: