/*
 * API Avito shop
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"context"
	"log"
	"net/http"

	sw "github.com/Experticon/avito_2025winter/internal/go-server-server-generated/go"

	"github.com/Experticon/avito_2025winter/pkg/client/postgresql"
)

func main() {
	log.Println("Server started on :8080")

	// Подключение к PostgreSQL
	ctx := context.Background()
	dbClient, err := postgresql.NewClient(ctx, 5, "localhost", "5432", "postgres", "1234", "avito_shop") // Параметры подключения можно настроить напрямую
	if err != nil {
		log.Fatalf("Failed to connect to PostgreSQL: %v", err)
	}
	defer dbClient.Close()

	// Создание маршрутизатора
	router := sw.NewRouter()

	// Запуск сервера
	log.Fatal(http.ListenAndServe(":8080", router))
}
