/*
 * API Avito shop
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"context"
	"log"
	"net/http"
	"os"

	sw "github.com/Experticon/avito_2025winter/internal/go-server-server-generated/go"

	"github.com/Experticon/avito_2025winter/pkg/client/postgresql"
)

/**
 * Тестовое задание для стажёра Backend-направления (зимняя волна 2025)
 * @author Абросимов Константин
 */

func main() {
	log.Println("Server started on :8080")

	// Подключение к PostgreSQL
	ctx := context.Background()
	var dbHost string
	if os.Getenv("DOCKER_ENV") == "true" {
		dbHost = "db" // Имя сервиса в Docker
	} else {
		dbHost = "localhost" // Локальная машина
	}

	dbClient, err := postgresql.NewClient(ctx, 5, dbHost, "5432", "postgres", "1234", "avito_shop")
	if err != nil {
		log.Fatalf("Failed to connect to PostgreSQL: %v", err)
	}
	defer dbClient.Close()

	// Создание маршрутизатора
	router := sw.NewRouter(dbClient)

	// Запуск сервера
	log.Fatal(http.ListenAndServe(":8080", router))
}
